### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by richvdh**
it seems to have several modules, and it isn't just about invites.

### CODE REVIEW

**Review by turt2live — APPROVED** [review]
lgtm, but this has diverged immensely from upstream so not sure if I'm the best person to request future reviews from.

**Comment by richvdh** [comment]
well, thanks for taking a look anyway.

**Comment by richvdh** [comment]
(are you sure? https://github.com/matrix-org/synapse-simple-antispam/commits/master doesn't show anything that hasn't been done by you or me)

**Comment by turt2live** [comment]
The hotreload branch ended up in production at some point, which I thought was on master

**Pull request merged**
